import {readdirSync} from 'node:fs';
import path from 'node:path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const years = readdirSync(path.join(process.cwd(), 'docs', 'notes'), {withFileTypes: true})
  .filter((entry) => entry.isDirectory() && /^\d{4}$/.test(entry.name))
  .map((entry) => entry.name)
  .sort();

const sidebars: SidebarsConfig = {
  docsSidebar: years.map((year) => ({
    type: 'category' as const,
    label: year,
    collapsed: false,
    link: {
      type: 'generated-index' as const,
      slug: `/${year}`,
      title: year,
      description: `Notes from ${year}.`,
    },
    items: [{type: 'autogenerated', dirName: `notes/${year}`}],
  })),
};

export default sidebars;
